---
- name: Installing dependencies necessary
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
    - docker-compose


- name: Add docker oficial GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present
    filename: docker

- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python3.12-venv
    state: latest
    update_cache: yes

- name: enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add Jenkins User to Docker group
  user:
    name: "{{ jenkins_user_docker }}"
    groups: docker
    append: yes

- name: Add Ubuntu user to docker group
  user:
    name: "ubuntu"
    groups: docker
    append: yes


