---
- name: Create monitoring directory
  file:
    path: /opt/monitoring
    state: directory

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /opt/monitoring/docker-compose.yml

- name: Copy prometheus.yml
  copy:
    src: prometheus.yml
    dest: /opt/monitoring/prometheus.yml

- name: Start containers with Docker Compose
  command: docker compose up -d
  args:
    chdir: /opt/monitoring

