- name: Configurar servidor Jenkins
  hosts: jenkins
  become: true

  vars:
    jenkins_url: "http://localhost:8080"
    jenkins_cli_jar_path: "/usr/local/bin/jenkins-cli.jar"
    jenkins_plugin_manager_path: "/usr/local/bin/jenkins-plugin-manager.jar"
    job_name: "CDB-3375-Final-Project"
    jenkins_user: "admin"
    jenkins_password: "admin"
    github_username: "{{ lookup('env', 'GITHUB_USER') }}"
    github_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"
    github_cred_id: "github-automatic-creds"
    jenkins_user_docker: "jenkins"

  roles:
    - docker
    - jenkins

