[devops]
99.79.54.86 ansible_user=ubuntu ansible_ssh_private_key_file=~/Documents/college/CDB-3375-FINAL-PROJECT/CDB-3375-final-project.pem

[jenkins]
35.183.243.129 ansible_user=ubuntu ansible_ssh_private_key_file=~/Documents/college/CDB-3375-FINAL-PROJECT/CDB-3375-final-project.pem

[webapp]
35.182.245.204 ansible_user=ubuntu ansible_ssh_private_key_file=~/Documents/college/CDB-3375-FINAL-PROJECT/CDB-3375-final-project.pem

