- name: Install Java
  apt:
    name: openjdk-17-jdk
    update_cache: yes
    state: present

- name: Download jenkins GPG key
  get_url:
      url: https://pkg.jenkins.io/debian/jenkins.io.key
      dest: /usr/share/keyrings/jenkins-keyring.asc
      mode: '0644'

- name: Add Jenkins repository with signed-by
  copy:
    dest: /etc/apt/sources.list.d/jenkins.list
    content: |
      deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/
    mode: '0644'

- name: Update packages
  apt:
    update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present

- name: Check correct permits on jenkins folders
  file:
    path: "{{ item }}"
    owner: jenkins
    group: jenkins
    recurse: yes
  loop:
    - /var/log/jenkins
    - /var/lib/jenkins
    - /var/cache/jenkins

- name: Start Jenkins
  service:
      name: jenkins
      state: started
      enabled: yes

- name: Disable Setup Wizard
  lineinfile:
    path: /etc/default/jenkins
    regexp: '^JAVA_ARGS='
    line: 'JAVA_ARGS="-Djenkins.install.runSetupWizard=false"'
    create: yes

- name: Create initialization scripts directories
  file:
    path: /var/lib/jenkins/init.groovy.d
    state: directory
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: Copy Groovy script to create admin user
  copy:
    src: create-admin.groovy
    dest: /var/lib/jenkins/init.groovy.d/create-admin.groovy
    owner: jenkins
    group: jenkins
    mode: '0644'

- name: Restart Jenkins to apply script
  systemd:
    name: jenkins
    state: restarted

- name: Copy plugins.txt file
  copy:
    src: plugins.txt
    dest: /var/lib/jenkins/plugins.txt
    owner: jenkins
    group: jenkins
    mode: '0644'

- name: Create Groovy script to GitHub credentials
  template:
    src: create_github_creds.groovy.j2
    dest: /var/lib/jenkins/init.groovy.d/create_github_creds.groovy
    owner: jenkins
    group: jenkins
    mode: '0755'

- name: Create SSH credentials in Jenkins
  template:
    src: templates/create-ssh-cred.groovy.j2
    dest: /tmp/create-ssh-cred.xml

- name: Create DockerHub credentials in Jenkins (UsernamePassword)
  shell: |
    cat <<EOF | java -jar {{ jenkins_cli_jar_path }} \
      -s {{ jenkins_url }} \
      -auth {{ jenkins_user }}:{{ jenkins_password }} \
      create-credentials-by-xml system::system::jenkins _ 
    <com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl>
      <scope>GLOBAL</scope>
      <id>{{ dockerhub_credential_id }}</id>
      <description>Credenciales DockerHub para Ansible</description>
      <username>{{ dockerhub_username }}</username>
      <password>{{ dockerhub_password }}</password>
    </com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl>
    EOF
  register: dockerhub_cred_creation
  ignore_errors: true
  tags: dockerhub


- name: Download jenkins-plugin-cli
  get_url:
    url: https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.13.2/jenkins-plugin-manager-2.13.2.jar
    dest: /usr/local/bin/jenkins-plugin-manager.jar
    mode: '0755'

- name: Install plugins with jenkins-plugin-cli
  command: >
    java -jar /usr/local/bin/jenkins-plugin-manager.jar
    --war /usr/share/java/jenkins.war
    --plugin-file /var/lib/jenkins/plugins.txt
    --plugin-download-directory /var/lib/jenkins/plugins

- name: Discard installation assistant for Jenkins
  copy:
     content: "2.516.1"
     dest: /var/lib/jenkins/jenkins.install.InstallUtil.lastExecVersion
     owner: jenkins
     group: jenkins
     mode: '0644'

- name: Discard upgrade wizard
  copy:
     content: "2.516.1"
     dest: /var/lib/jenkins/jenkins.install.UpgradeWizard.state
     owner: jenkins
     group: jenkins
     mode: '0644'

- name: copy job-config.xml
  copy:
    src: files/job-config.xml
    dest: /tmp/job-config.xml
    mode: '0644'

- name: Download jenkins-cli.jar
  get_url:
    url: "{{ jenkins_url }}/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_cli_jar_path }}"
    mode: '0755'
    force: yes

- name: Check jenkins user and jenkins password values
  debug:
    msg: "Usuario: {{ jenkins_user }}, Password: {{ jenkins_password }}"

- name: Create Jenkins job with authentication
  shell: |
    java -jar {{ jenkins_cli_jar_path }} \
    -s {{ jenkins_url }} \
    -http \
    -auth {{ jenkins_user }}:{{ jenkins_password }} \
    create-job {{ job_name }} < /tmp/job-config.xml

- name: Create SSH credentials
  shell: |
    java -jar {{ jenkins_cli_jar_path }} \
    -s {{ jenkins_url }} \
    -auth {{ jenkins_user }}:{{ jenkins_password }} \
    create-credentials-by-xml system::system::jenkins _ < /tmp/create-ssh-cred.xml

- name: Create jenkins node
  set_fact:
    node_name: "jenkins"
    node_description: "Local Agent connect by ssh"
    node_user: "ubuntu"
    node_port: 22
    ssh_credential_id: "ec2-ssh-key"
    executors: 1
    node_mode: "NORMAL"
    node_labels: "jenkins"
    node_host: "127.0.0.1"

- name: Generate node XML configuration file
  template:
    src: node-config.xml.j2
    dest: "/tmp/{{ node_name }}.xml"

- name: Create Jenkis node
  shell: |
    java -jar {{ jenkins_cli_jar_path }} \
    -s {{ jenkins_url }} \
    -auth {{ jenkins_user }}:{{ jenkins_password }} \
    create-node {{ node_name }} < /tmp/{{ node_name }}.xml
  register: cli_output
  ignore_errors: true  # Evita fallo si ya existe

- name: Mostrar resultado del CLI
  debug:
    var: cli_output.stdout


- name: Crear nodo devopstools en Jenkins con Jenkins CLI
  set_fact:
    # Nodo devopstools
    node_name: "devopstools"
    node_description: "Nodo para pruebas UI con Selenium"
    node_user: "ubuntu"
    node_port: 22
    ssh_credential_id: "ec2-ssh-key"
    executors: 1
    node_mode: "NORMAL"             # "NORMAL" o "EXCLUSIVE"
    node_labels: "devopstools"
    node_host: "99.79.54.86"


- name: Mostrar IP del nodo
  debug:
    msg: "IP del nodo devopstools: {{ node_host }}"

- name: Generar XML del nodo
  template:
    src: node-config.xml.j2
    dest: /tmp/{{ node_name }}.xml

- name: Crear nodo remoto en Jenkins
  shell: |
    java -jar {{ jenkins_cli_jar_path }} \
    -s {{ jenkins_url }} \
    -auth {{ jenkins_user }}:{{ jenkins_password }} \
    create-node {{ node_name }} < /tmp/{{ node_name }}.xml

  register: cli_output

- name: Mostrar salida de Jenkins CLI
  debug:
    var: cli_output.stdout

- name: Crear nodo remoto 'webapp' en Jenkins vía SSH
  set_fact:
    node_name: "webapp"
    node_description: "Agente remoto webapp conectado por SSH"
    node_user: "ubuntu"
    node_port: 22
    ssh_credential_id: "ec2-ssh-key"
    executors: 1
    node_mode: "NORMAL"
    node_labels: "webapp"
    node_host: "35.182.245.204"

- name: Generar archivo XML de configuración del nodo
  template:
    src: node-config.xml.j2
    dest: "/tmp/{{ node_name }}.xml"

- name: Crear nodo con Jenkins CLI
  shell: |
    java -jar {{ jenkins_cli_jar_path }} \
    -s {{ jenkins_url }} \
    -auth {{ jenkins_user }}:{{ jenkins_password }} \
    create-node {{ node_name }} < /tmp/{{ node_name }}.xml
  register: cli_output
  ignore_errors: true  # Evita fallo si ya existe

- name: Mostrar resultado del CLI
  debug:
    var: cli_output.stdout



- name: Reiniciar Jenkins para aplicar el script
  systemd:
    name: jenkins
    state: restarted

